server:
  port: 10010
spring:
  #过滤返回值为null 空
  jackson:
    default-property-inclusion: non_null
  application:
    name: card
  datasource:
    url: jdbc:mysql://111.230.250.188:3306/bmp?characterEncoding=UTF-8
    username: bmp
    password: bmp
ly:
  jwt:
    secret: ly@Login(Auth}*^31)&ztr6%f3q2 # 登录校验的密钥
    pubKeyPath: /rsa.pub # 公钥地址
    priKeyPath: /rsa.pri # 私钥地址
    expire: 5256000 # 过期时间,单位分钟   10年不过期
    cookieName: LY_TOKEN
    cookieMaxAge: 1800


wx:
  config:
    appid: wx8aaffc8ca4853e25
    secret: e0d2a4b8c7f8dd37a56ed3aaedf68696

# 自定义文件上传路径
web:
  # ffmpeg_path: C:/image/ffmpeg.exe
  image: jpeg,jpg,png,bmp
  video: avi,mp4,flv

  upload-path:
    /video  #这里末尾没有/斜杠
  domain: http://yfteach.cn/video   #末尾没有 / 斜杠

#跨域的前台域名
cors:
  url: http://localhost